# This is a basic workflow to help you get started with Actions

name: Nightly

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      # Runs a single command using the runners shell
      - name: Run Python script
        id: get_filepath
        run: |
          echo "file_path=$(python CreatePlugin.py)" >> $GITHUB_OUTPUT

      - name: Zipping files
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -q -j -r dir.zip src

      - name: Rename to crplugin
        run: |
          mv dir.zip '${{ steps.get_filepath.outputs.file_path }}'
          
      - name: Update git tag
        run: |
          git tag -f nightly
          git push -f origin nightly
          
      - name: Update Nightly Release
        uses: ncipollo/release-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ steps.get_filepath.outputs.file_path }}
          tag: "nightly"
          commit: main
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          removeArtifacts: true
